spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/wms_dev_db
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    com.wms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE