spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/wms_saas_dev
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    com.wms: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
