spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

logging:
  level:
    root: WARN
    com.wms: INFO